import Mathlib.Order.Nucleus
import Mathlib.Order.Sublocale
import Mathlib.Order.Heyting.Regular

/-!
# Nuclei and sublocales — the home of "a predicated difference generates a system"

**The recognized structure.** In the theory of **nuclei and sublocales** — the point-free
(locale-theoretic) shadow of **Lawvere–Tierney topologies** — a modality generates a system and the
systems form a lattice. On the frame `X` of a system's propositions/opens:
- a **nucleus** `j : X → X` (inflationary, idempotent, meet-preserving) is a *modality* — a closure
  operator (`Nucleus.toClosureOperator`);
- each nucleus **generates a system**: its **sublocale** (`Nucleus.toSublocale`), whose carrier is
  itself a frame — a genuine sub-system;
- the generated systems **form a lattice**: the nuclei are a `Frame` and the sublocales a `Coframe`,
  identified order-dually by `nucleusIsoSublocale`.

**The conjecture this file places (Tim, independent of this project, fused with its axis-2 finding).** A
self-referential object does not carry its own verdict; the *system* it lands in is generated by the
*difference predicated* against it — predicating a difference creates a system, the object alone does
not, and the systems so generated form a lattice. That is the informal reading *of* the nucleus/sublocale
correspondence above (a modality is a predicated difference; its sublocale is the generated system); the
correspondence is its rigorous home, not a verbatim restatement of it. This file **states no new result**
— it *identifies* the conjecture with recognized structure and routes Mathlib's theorems.

**Credit (both directions recognized):** the machinery is nucleus/sublocale theory (nLab: *nucleus*,
*sublocale*; the point-free Lawvere–Tierney topology). The *reading* of it as "opposition / difference
generates structure" is **Lawvere's categorical dialectics** — adjoint functors and the Aufhebung as the
unity of opposites (F. W. Lawvere, "Unity and identity of opposites in calculus and physics", *Applied
Categorical Structures* 4 (1996)). The Zero Paradox framework **joins** this program, it does not own it.
*Conjecturally, and not formalized here:* its axis-2 category-relativity (`Category/DiagonalWitness.lean`
— the same diagonal object is a wall in one system and a floor in another) would be a move in the sublocale
lattice, and the diagonal-witness map-class topology a shadow of it. The uncopied placement remains only
the framework's own ⊥ as the shared floor.

## Engineer's Take

A dive into difference as a generating system, ranging from logic and typeclass to research on the nature
of Classical.choice and the double negation operator.
-/

namespace ZeroParadox

open Order

section
variable {X : Type*} [Order.Frame X]

/-! ### § The identification — predicated difference (nucleus) ⇒ system (sublocale) ⇒ lattice of systems -/

/-- A predicated difference on a system is a **nucleus** on its frame of propositions. -/
example (j : Nucleus X) (a : X) : a ≤ j a := j.le_apply

/-- A nucleus IS a closure operator — predicating a difference is a closure (idempotent, inflationary). -/
noncomputable example (j : Nucleus X) : ClosureOperator X := j.toClosureOperator

/-- Each predicated difference **generates a system**: its sublocale. -/
example (j : Nucleus X) : Sublocale X := j.toSublocale

/-- The generated systems form a lattice (the sublocales are a `Coframe`); the differences form a
    `Frame`; and `nucleusIsoSublocale` identifies the two order-dually. -/
example : Order.Frame (Nucleus X) := inferInstance
example : Order.Coframe (Sublocale X) := inferInstance
#check @nucleusIsoSublocale X _

/-! ### § Non-vacuity — the two extreme predicated differences and their systems

Predicate nothing (the identity, `⊥` in the nucleus lattice) and the system is the whole locale;
predicate everything (`⊤`) and it collapses to the trivial one-object system. Every genuine modality —
double negation (the classical core), the open/closed nuclei — sits strictly between, each carving out
its own system, exactly as the conjecture says. -/
example : (⊥ : Nucleus X) ≤ (⊤ : Nucleus X) := bot_le

end

/-! ### § The canonical predicated difference — double negation generates the classical (Boolean) core

The sharpest instance of "a predicated difference generates a system": the difference is **double
negation** `a ↦ aᶜᶜ`, and the system it generates is the **classical (Boolean) core** of the constructive
base. On a Heyting algebra — the algebra of intuitionistic propositions — the double-negation map is a
closure (inflationary, `a ≤ aᶜᶜ`, and a reflection); its fixed points are the **regular** elements; and
those form a `BooleanAlgebra` (Mathlib's `Heyting.Regular`). That is the algebraic counterpart of
**Glivenko's theorem** ("the constructive base under the `¬¬` difference is classical") — the
`¬¬`-Boolean subtopos, textbook and cited here, not claimed.

**The honest fence (logic, not choice).** What this difference generates is classical *logic* (excluded
middle, the Boolean core), NOT the axiom of *choice*. **Choice implies excluded middle (Diaconescu 1975)**
— and in Lean's own kernel `Classical.em` is derived from `Classical.choice` by exactly that argument.
That **full** choice is strictly stronger than excluded middle is **Cohen 1963** / Fraenkel–Mostowski
independence, *not* Diaconescu, whose own theorem is an **equivalence** for the restricted shape (choice
for inhabited subobjects of a two-element object is excluded middle). So: double negation is the
difference that generates the classical core, and full choice sits above it. See
`ZeroParadox/Category/ChoiceCannotBe.lean` for the precise attributions. Stated below
with `example`s only (no new declarations) — this file *identifies*, it does not add a result. -/

section
variable {α : Type*} [HeytingAlgebra α]

/-- The canonical predicated difference is a **closure**: passing to the double-negation (classical) view
    only moves up. -/
example (a : α) : a ≤ aᶜᶜ := le_compl_compl

/-- **Regularization is double negation** — the operator that "picks a side" is `a ↦ aᶜᶜ`
    (`Heyting.Regular.toRegular`). -/
example (a : α) : (Heyting.Regular.toRegular a : α) = aᶜᶜ := Heyting.Regular.coe_toRegular a

/-- The system the difference generates — the `¬¬`-regular elements — is a **Boolean algebra**
    (`Heyting.Regular`'s instance). The informal reading: "double negation generates the classical
    (Boolean) core." -/
example : BooleanAlgebra (Heyting.Regular α) := inferInstance

/-- The Boolean core is the **reflection** of the constructive base along double negation: the generated
    system sits inside the base as a `GaloisInsertion` — the nucleus/sublocale pattern one level down (a
    Heyting algebra suffices; no `Order.Frame` needed). -/
example : GaloisInsertion (Heyting.Regular.toRegular (α := α)) ((↑) : Heyting.Regular α → α) :=
  Heyting.Regular.gi

end

end ZeroParadox
