import Mathlib.Order.Nucleus
import Mathlib.Order.Sublocale

/-!
# Predicating a difference generates a system — the nucleus / sublocale identification

**The conjecture (Tim, independent of this project, fused with its axis-2 finding):** a
self-referential object does not carry its own verdict; the *system* it lands in is generated by the
**difference you predicate** against it. Predicating a difference creates a system; the object alone
does not — and the systems so generated form a lattice.

**Its rigorous home is the theory of nuclei and sublocales** — the point-free (locale-theoretic) shadow
of **Lawvere–Tierney topologies**. On the frame `X` of a system's propositions/opens:
- a **nucleus** `j : X → X` (inflationary, idempotent, meet-preserving) is a *modality* — precisely a
  way of *predicating a difference* (a closure operator, `Nucleus.toClosureOperator`);
- each nucleus **generates a system**: its **sublocale** (`Nucleus.toSublocale`), whose carrier is
  itself a frame — a genuine sub-system;
- the generated systems **form a lattice**: the nuclei are a `Frame` and the sublocales a `Coframe`,
  identified order-dually by `nucleusIsoSublocale`.

So "predicating a difference generates a system, and the systems form a lattice" is, verbatim, the
nucleus/sublocale correspondence. This file **states no new result** — it *identifies* the conjecture
with recognized structure and routes Mathlib's theorems.

**Credit (both directions recognized):** the machinery is nucleus/sublocale theory (nLab: *nucleus*,
*sublocale*; the point-free Lawvere–Tierney topology). The *reading* of it as "opposition / difference
generates structure" is **Lawvere's categorical dialectics** — adjoint functors and the Aufhebung as the
unity of opposites (F. W. Lawvere, "Unity and identity of opposites in calculus and physics", *Applied
Categorical Structures* 4 (1996)). The Zero Paradox framework **joins** this program, it does not own it:
its axis-2 category-relativity (`Category/DiagonalWitness.lean` — the same diagonal object is a wall in
one system and a floor in another) is a move in the sublocale lattice, and the diagonal-witness map-class
topology is a shadow of it. The uncopied placement remains only the framework's own ⊥ as the shared floor.

## Engineer's Take

TODO (Tim): your take on "the system is generated by the predicated difference, not carried by the
object" — that this is the nucleus/sublocale (Lawvere–Tierney / Lawvere-dialectics) structure, and where
the framework sits inside it.
-/

namespace ZeroParadox

open Order

section
variable {X : Type*} [Order.Frame X]

/-! ### § The identification — predicated difference (nucleus) ⇒ system (sublocale) ⇒ lattice of systems -/

/-- A predicated difference on a system is a **nucleus** on its frame of propositions. -/
example (j : Nucleus X) (a : X) : a ≤ j a := j.le_apply

/-- A nucleus IS a closure operator — predicating a difference is a closure (idempotent, inflationary). -/
noncomputable example (j : Nucleus X) : ClosureOperator X := j.toClosureOperator

/-- Each predicated difference **generates a system**: its sublocale. -/
example (j : Nucleus X) : Sublocale X := j.toSublocale

/-- The generated systems form a lattice (the sublocales are a `Coframe`); the differences form a
    `Frame`; and `nucleusIsoSublocale` identifies the two order-dually. -/
example : Order.Frame (Nucleus X) := inferInstance
example : Order.Coframe (Sublocale X) := inferInstance
#check @nucleusIsoSublocale X _

/-! ### § Non-vacuity — the two extreme predicated differences and their systems

Predicate nothing (the identity, `⊥` in the nucleus lattice) and the system is the whole locale;
predicate everything (`⊤`) and it collapses to the trivial one-object system. Every genuine modality —
double negation (the classical core), the open/closed nuclei — sits strictly between, each carving out
its own system, exactly as the conjecture says. -/
example : (⊥ : Nucleus X) ≤ (⊤ : Nucleus X) := bot_le

end

end ZeroParadox
