#!/usr/bin/env python3
"""Corpus-wide verification report, for the public CI run summary.

Reads a full `lake build` log and emits Markdown saying what the machine actually
checked: whether the corpus verified, and the axiom footprint of every declaration
that declares one. Nothing is written to the repository - the log is CI's, the
report is CI's, and both regenerate from source on every run.

Generalizes scripts/minimal_core_report.py, which does this for one file.

Exits 0 if the corpus verified (no error, no sorry), 1 otherwise, so the report
doubles as a gate.

Usage: corpus_verification_report.py <lake-build-log>
"""
import sys
import re
from collections import Counter, defaultdict

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

if len(sys.argv) < 2:
    sys.stderr.write("usage: corpus_verification_report.py <lake-build-log>\n")
    sys.exit(2)

path = sys.argv[1]
print(f"[report] reading {path}", file=sys.stderr)
log = open(path, encoding="utf-8", errors="replace").read()
print(f"[report] {len(log)} chars, {log.count(chr(10))} lines", file=sys.stderr)

# --- verification status -------------------------------------------------
# NOT a substring test for "sorry": 21 corpus files carry the word in prose,
# in lines like "all axiom proofs sorry-free", and a substring test fails them
# for announcing that they are clean. Lean's actual warning uses BACKTICKS -
# measured 2026-08-08 against the pinned toolchain, do not retype from memory.
SORRY_WARNING = "declaration uses `sorry`"

has_error = "error:" in log
has_sorry = SORRY_WARNING in log
ok = not has_error and not has_sorry
print(f"[report] error={has_error} sorry={has_sorry} -> ok={ok}", file=sys.stderr)

# --- axiom footprints ----------------------------------------------------
# Emitted by the ~1200 `#print axioms` calls the corpus already carries.
axfree = re.findall(r"'([^']+)' does not depend on any axioms", log)
axdep = re.findall(r"'([^']+)' depends on axioms: \[([^\]]*)\]", log)
print(f"[report] {len(axfree)} axiom-free, {len(axdep)} with a footprint", file=sys.stderr)

by_footprint = Counter()
for _name, ax in axdep:
    by_footprint[", ".join(a.strip() for a in ax.split(","))] += 1

# --- the report ----------------------------------------------------------
total = len(axfree) + len(axdep)

out = []
out.append("## The corpus — checked by machine, not by us ✓" if ok
           else "## The corpus — VERIFICATION FAILED ✗")
out.append("")
if not ok:
    reason = "a step failed" if has_error else "a declaration was left unproven"
    out.append(f"**The proof assistant did NOT accept this build — {reason}.** "
               "The raw output is in the run log above.")
elif total:
    # Only claim the evidence when the evidence is actually here.
    out.append(
        "Don't take our word for any of it. Every declaration below was re-checked by "
        "Lean, a proof assistant whose only job is to reject a false step, and it passed "
        "with nothing left unproven. The list is generated by this run, not maintained by "
        "hand, so it cannot drift from what was actually proved.")
else:
    out.append(
        "Lean accepted this build: no errors, nothing left unproven. It rebuilt nothing, "
        "though, so this run produced no per-declaration evidence to show.")
out.append("")

# A warm .lake cache means Lake rebuilds nothing and Lean re-emits nothing, so an
# empty table would read as "verified, and here is the evidence" when the truth is
# "this run reused a cache and produced no evidence". Say which it was.
if total == 0:
    out.append("Clear the Actions cache and re-run to regenerate the footprint table.")
    out.append("")
    sys.stdout.write("\n".join(out) + "\n")
    print("[report] no footprints in log (warm cache?) - reported honestly", file=sys.stderr)
    sys.exit(0 if ok else 1)

out.append(f"**Declarations with a recorded axiom footprint:** {total}")
out.append("")
out.append("| footprint | count | means |")
out.append("|---|---:|---|")
if axfree:
    out.append(f"| *(none)* | {len(axfree)} | proved from the bare logic — no classical "
               "reasoning, no quotients, nothing assumed |")
GLOSS = {
    "propext": "propositional extensionality only",
    "propext, Quot.sound": "extensionality and quotients; still choice-free",
    "propext, Classical.choice, Quot.sound": "the ordinary Mathlib footprint, including choice",
}
for fp, n in by_footprint.most_common():
    out.append(f"| `{fp}` | {n} | {GLOSS.get(fp, 'see the Lean output above')} |")
out.append("")

if axfree:
    out.append("<details><summary>The choice-free declarations, by name</summary>")
    out.append("")
    for name in sorted(axfree):
        out.append(f"- `{name}`")
    out.append("")
    out.append("</details>")
    out.append("")

out.append(
    "**Scope:** these are the declarations *this run* elaborated - a warm cache means "
    "unchanged modules are not rebuilt and so do not appear. An axiom footprint says what "
    "a proof depends on; it says nothing about whether a theorem is interesting or "
    "correctly named.")

sys.stdout.write("\n".join(out) + "\n")
print(f"[report] wrote {len(out)} lines, exiting {0 if ok else 1}", file=sys.stderr)
sys.exit(0 if ok else 1)
